### PR TITLE
Start documentation

### PR DESCRIPTION
**Pull request by jl-wynen**

### CODE REVIEW

**Review by nitrosx — APPROVED** [review]

**Review by nitrosx — COMMENTED** [review]
Can you confirm that the following sessions are empty or to be completed:
- Getting Started
- Classes
- Free functions
- Modules
- Getting Started
- Dependencies

**Comment by nitrosx** [comment]
In Coding conventions, can we insert also an example that is included in the code and where to find it?

**Comment by nitrosx** [comment]
Under release notes, you have an additional menu on the right side of the page. Can we integrate that in the left pane.
Screenshot from 2022-11-16 13-31-39

**Comment by nitrosx** [comment]
I would move "On this page" on the right side together with the menu on the left and expand the space for the content.

Everything looks good

**Comment by jl-wynen** [comment]
> In Coding conventions, can we insert also an example that is included in the code and where to find it?

There is no complete example in the code. But people can just open any source file and look at the docstrings if the given example is not enough

**Pull request merged**
